[package]
name = "topaz-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's' # try also 'z'

[dependencies]
wasm-bindgen = "0.2.95"
web-sys = "0.3.72"
topaz = { path = "../topaz" }