# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  assembler:
    kind: file
    path: "log/assembler.log"
    encoder:
      pattern: "{d} - {m}{n}"

root:
  level: warn
  appenders:
    - stdout

loggers:
  assembler:
    level: info
    appenders: 
      - assembler